apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
data:
  database-host: Y291bnRlci1kYXRhYmFzZQ==        # "counter-database"
  database-name: ZGF0YWJhc2U=                  # "database"
  database-user: cG9zdGdyZXM=                  # "postgres"
  database-password: cGFzc3dvcmQ=              # "password"
 